name: Hackathon

on:
  workflow_dispatch:
    inputs:
      targetEnv:
        type: choice
        description: Target Environment
        options: 
        - terraform-dev1-plan-apply
        - cs-hackathon
      actionType:
        type: choice
        description: Action Type
        options: 
        - Create Resource Group - Plan
        - Create Resource Group - Apply


permissions:
      id-token: write
      contents: read

jobs:
  
  CreateResourceGroupPlan:
    name: 'Create Resource Group - Plan'
    if: github.event.inputs.actionType == 'Create Resource Group - Plan'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TARGET_ENV: ${{ github.event.inputs.targetEnv }}
    runs-on: [self-hosted,Linux,X64,openid]
   
    

    defaults:
      run:
        shell: bash
        working-directory: ./az-serverless-demo

    steps:
      - name: 'Code checkout'
        uses: actions/checkout@v2
        
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          environment: ${{ env.TARGET_ENV }}

      
      - name: check current directory
        id: basic_cli_command
        run: |
          pwd
          ls

      - name: Terraform Init
        run: terraform init 
        
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=deploy.tfplan -var-file="./env/gt/env.tfvars"
      
      # Generate Infracost JSON file as the baseline.
      - name: Generate Infracost cost estimate baseline
        run: infracost breakdown --path=./ --format=json --out-file=/tmp/terraform_state/infracost-base.json
      # Generate an Infracost diff and save it to a JSON file.
      - name: Generate Infracost diff
        run: infracost diff --path=./ --format=json --compare-to=/tmp/terraform_state/infracost-base.json --out-file=/tmp/terraform_state/infracost.json

      - name: Post Infracost comment
        run: infracost breakdown --path .
  
  CreateResourceGroupApply:
    name: 'Create Resource Group - Apply'
    if: github.event.inputs.actionType == 'Create Resource Group - Apply'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TARGET_ENV: ${{ github.event.inputs.targetEnv }}
    runs-on: [self-hosted,Linux,X64,openid]
    

    defaults:
      run:
        shell: bash
        working-directory: ./az-serverless-demo

    steps:
      - name: 'Code checkout'
        uses: actions/checkout@v2
        
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          environment: ${{ env.TARGET_ENV }}

      
      - name: check current directory
        id: basic_cli_command
        run: |
          pwd
          ls

      - name: Terraform Init
        run: terraform init 
        
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=deploy.tfplan -var-file="./env/gt/env.tfvars"
      
      # Generate Infracost JSON file as the baseline.
      - name: Generate Infracost cost estimate baseline
        run: infracost breakdown --path=./ --format=json --out-file=/tmp/terraform_state/infracost-base.json
      # Generate an Infracost diff and save it to a JSON file.
      - name: Generate Infracost diff
        run: infracost diff --path=./ --format=json --compare-to=/tmp/terraform_state/infracost-base.json --out-file=/tmp/terraform_state/infracost.json

      - name: Post Infracost comment
        run: infracost breakdown --path .
        #infracost comment github --path=/tmp/terraform_state/infracost.json --repo=$GITHUB_REPOSITORY --github-token=${{github.token}} --behavior=update
        
      - name: Terraform Apply
        run: terraform apply --auto-approve "deploy.tfplan"
      
      